"""Deterministic in-memory `LLMClient` for offline tests and CLI dry-runs.

`MockClient` is keyed by `provider` and `model` (so cost/usage accounting and
judge IDs look indistinguishable from a real run) but never touches the
network. The response is generated by a user-supplied callable; the default
callable returns a payload matching whichever tool the caller forced via
`tools=[...]`, so the same mock works for both rubric judges
(`record_score`) and LLM-as-NLI calls (`record_nli`).

When `temperature > 0`, results are also keyed by an internal call counter
so successive sampling-pass invocations produce *different* draws — this
is how `--mock` exercises self-consistency and semantic-entropy wiring.
"""

from __future__ import annotations

import hashlib
import itertools
from collections.abc import Callable
from dataclasses import dataclass, field

from panoptes.clients.base import (
    CompletionResponse,
    Message,
    SystemBlock,
    ToolChoice,
    ToolSpec,
    price_call,
)
from panoptes.schemas import TokenUsage

ResponseFn = Callable[
    [list[Message], list[SystemBlock] | None, list[ToolSpec] | None, float, int],
    CompletionResponse,
]


def _hash_score(text: str, salt: int = 0) -> float:
    digest = hashlib.sha256(f"{salt}|{text}".encode()).digest()
    score = 0.2 + (int.from_bytes(digest[:2], "big") / 0xFFFF) * 0.8
    return round(score, 4)


def _default_response(
    messages: list[Message],
    _system: list[SystemBlock] | None,
    tools: list[ToolSpec] | None,
    temperature: float,
    call_counter: int,
) -> CompletionResponse:
    """Default mock that returns whichever tool's schema was requested.

    - temp=0 (point pass): score depends only on the message text.
    - temp>0 (sampling pass): score also depends on `call_counter`, so
      successive draws differ — needed for sampling-based UQ wiring.
    - When the forced tool is `record_nli`, return a hash-derived entailment
      payload so the LLM-as-NLI backend works under `--mock`.
    """
    seed_text = "\n".join(m.content for m in messages)
    salt = 0 if temperature == 0.0 else call_counter
    score = _hash_score(seed_text, salt=salt)
    tool_name = tools[0].name if tools else "record_score"

    tool_calls: dict[str, dict[str, object]]
    if tool_name == "record_nli":
        labels = ["entailment", "neutral", "contradiction"]
        idx = int(_hash_score(seed_text, salt=salt + 7) * 3) % 3
        tool_calls = {
            "record_nli": {
                "label": labels[idx],
                "confidence": 0.6 + (idx * 0.1),
            }
        }
    else:
        tool_calls = {
            tool_name: {
                "value": score,
                "scale": "continuous",
                "rationale": (
                    f"Mock judge sample (temp={temperature}, salt={salt}): score={score}"
                ),
                "flags": [],
            }
        }
    usage = TokenUsage(input_tokens=200, output_tokens=60)
    return CompletionResponse(
        text="",
        tool_calls=tool_calls,
        usage=usage,
        cost_usd=0.0,
        latency_ms=1.0,
        raw={"_mock": True},
    )


@dataclass(slots=True)
class MockClient:
    """In-memory `LLMClient` for tests and `--mock` CLI runs."""

    provider: str = "mock"
    model: str = "mock-model"
    response_fn: ResponseFn = _default_response
    _counter: itertools.count[int] = field(
        default_factory=lambda: itertools.count(0), init=False
    )

    async def complete(
        self,
        messages: list[Message],
        *,
        system: list[SystemBlock] | None = None,
        tools: list[ToolSpec] | None = None,
        tool_choice: ToolChoice | None = None,
        max_tokens: int = 1024,
        temperature: float = 0.0,
        stop_sequences: list[str] | None = None,
    ) -> CompletionResponse:
        call_idx = next(self._counter)
        response = self.response_fn(messages, system, tools, temperature, call_idx)
        # Recompute cost from usage so accounting reflects whatever the
        # caller-supplied response_fn returned.
        response.cost_usd = price_call(self.model, response.usage)
        return response

    async def aclose(self) -> None:
        return None
