"""Deterministic in-memory `LLMClient` for offline tests and CLI dry-runs.

`MockClient` is keyed by `provider` and `model` (so cost/usage accounting and
judge IDs look indistinguishable from a real run) but never touches the
network. The response is generated by a user-supplied callable that takes the
parsed messages and returns a `CompletionResponse`. The default callable
produces a `record_score` tool call with a deterministic score derived from
a hash of the user message, suitable for end-to-end pipeline smoke tests.
"""

from __future__ import annotations

import hashlib
from collections.abc import Callable
from dataclasses import dataclass

from panoptes.clients.base import (
    CompletionResponse,
    Message,
    SystemBlock,
    ToolChoice,
    ToolSpec,
    price_call,
)
from panoptes.schemas import TokenUsage

ResponseFn = Callable[[list[Message], list[SystemBlock] | None], CompletionResponse]


def _default_response(
    messages: list[Message], _system: list[SystemBlock] | None
) -> CompletionResponse:
    """Hash-derived deterministic score in [0.2, 1.0] with a tool-call payload.

    The mapping `hash(text) -> score` ensures repeated invocations on the
    same input return the same result, mimicking `temperature=0` semantics
    without an actual model. We avoid scores below 0.2 because real judges
    rarely score above 0.0 in practice when given a non-degenerate response.
    """
    seed_bytes = "\n".join(m.content for m in messages).encode("utf-8")
    digest = hashlib.sha256(seed_bytes).digest()
    score = 0.2 + (int.from_bytes(digest[:2], "big") / 0xFFFF) * 0.8
    score = round(score, 4)
    usage = TokenUsage(input_tokens=200, output_tokens=60)
    return CompletionResponse(
        text="",
        tool_calls={
            "record_score": {
                "value": score,
                "scale": "continuous",
                "rationale": "Mock judge: deterministic hash-derived score for offline runs.",
                "flags": [],
            }
        },
        usage=usage,
        cost_usd=0.0,
        latency_ms=1.0,
        raw={"_mock": True, "score": score},
    )


@dataclass(slots=True)
class MockClient:
    """In-memory `LLMClient` for tests and `--mock` CLI runs."""

    provider: str = "mock"
    model: str = "mock-model"
    response_fn: ResponseFn = _default_response

    async def complete(
        self,
        messages: list[Message],
        *,
        system: list[SystemBlock] | None = None,
        tools: list[ToolSpec] | None = None,
        tool_choice: ToolChoice | None = None,
        max_tokens: int = 1024,
        temperature: float = 0.0,
        stop_sequences: list[str] | None = None,
    ) -> CompletionResponse:
        response = self.response_fn(messages, system)
        # Recompute cost from usage so accounting reflects whatever the
        # caller-supplied response_fn returned.
        response.cost_usd = price_call(self.model, response.usage)
        return response

    async def aclose(self) -> None:
        return None
