import { Card, CardTitle } from "@/components/Card";
import { JudgeBadge } from "@/components/JudgeBadge";
import { ParetoChart } from "@/components/ParetoChart";
import {
  loadCalibration,
  loadHeadlineRuns,
  loadPareto,
} from "@/lib/data";
import { formatPercent, gapColor, shortJudge } from "@/lib/format";

export default function CalibrationPage() {
  const calib = loadCalibration();
  const runs = loadHeadlineRuns();
  // Show Pareto from the most informative run (biggest n_calls usually = best curve)
  const featured = [...runs].sort((a, b) => b.n_calls - a.n_calls)[0];
  const pareto = featured ? loadPareto(featured.run_id) : [];

  if (!calib) {
    return (
      <Card>
        <div className="muted text-sm">No calibration data exported yet. Run scripts/calibration_probe.py and rerun the export.</div>
      </Card>
    );
  }

  return (
    <div className="flex flex-col gap-10">
      <header>
        <CardTitle>calibration probe</CardTitle>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">
          Conformal coverage on real ground truth
        </h1>
        <p className="mt-2 max-w-3xl muted">
          {calib.candidates.n} obfuscated HumanEval problems. A candidate solution is generated by{" "}
          <span className="font-mono">{calib.generator.model}</span> at temperature{" "}
          {calib.generator.temperature}, graded by sandboxed test execution (real pass/fail label),
          then judged by two LLM judges. Split conformal is fit on a 50/50 calibration/test split.
        </p>
      </header>

      <Card className="border-emerald-500/30">
        <CardTitle>headline</CardTitle>
        <div className="mt-2 text-2xl md:text-3xl font-semibold tracking-tight">
          <span className="text-emerald-500">{formatPercent(calib.headline.empirical, 0)}</span>{" "}
          empirical coverage at the nominal {formatPercent(calib.headline.nominal, 0)} target ·{" "}
          <span className="text-emerald-500">{calib.headline.gap_pp.toFixed(1)}pp gap</span>
        </div>
        <p className="mt-3 max-w-3xl text-sm muted leading-relaxed">{calib.headline.summary}</p>
      </Card>

      <section>
        <CardTitle>coverage table</CardTitle>
        <div className="mt-3 surface rounded-2xl overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wider muted" style={{ background: "var(--surface-2)" }}>
                <th className="px-4 py-3">judge</th>
                <th className="px-4 py-3 text-right">α</th>
                <th className="px-4 py-3 text-right">nominal (1−α)</th>
                <th className="px-4 py-3 text-right">empirical</th>
                <th className="px-4 py-3 text-right">|emp − nom|</th>
                <th className="px-4 py-3 text-right">q</th>
                <th className="px-4 py-3 text-right">n_cal</th>
                <th className="px-4 py-3 text-right">n_test</th>
              </tr>
            </thead>
            <tbody>
              {calib.conformal_coverage.map((row, i) => {
                const gap = gapColor(row.gap_pp);
                const gapClass =
                  gap === "good"
                    ? "text-emerald-500"
                    : gap === "ok"
                      ? "text-amber-400"
                      : "text-rose-400";
                return (
                  <tr key={i} className="border-t" style={{ borderColor: "var(--border)" }}>
                    <td className="px-4 py-3">
                      <JudgeBadge judgeId={row.judge} />
                    </td>
                    <td className="px-4 py-3 text-right font-mono tabular-nums">{row.alpha.toFixed(2)}</td>
                    <td className="px-4 py-3 text-right font-mono tabular-nums">{row.nominal.toFixed(2)}</td>
                    <td className="px-4 py-3 text-right font-mono tabular-nums">{row.empirical.toFixed(2)}</td>
                    <td className={`px-4 py-3 text-right font-mono tabular-nums ${gapClass}`}>
                      {row.gap_pp.toFixed(1)}pp
                    </td>
                    <td className="px-4 py-3 text-right font-mono tabular-nums muted">{row.q.toFixed(3)}</td>
                    <td className="px-4 py-3 text-right font-mono tabular-nums muted">{row.n_cal}</td>
                    <td className="px-4 py-3 text-right font-mono tabular-nums muted">{row.n_test}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div className="mt-3 text-xs muted leading-relaxed">
          Color: green ≤ 5pp · amber ≤ 10pp · red &gt; 10pp. The theorem guarantees coverage ≥ 1−α,
          not = 1−α — over-covering rows are the safe-side direction (conservative intervals).
        </div>
      </section>

      <section>
        <CardTitle>coverage–width Pareto (inter-judge spread)</CardTitle>
        {featured && (
          <div className="text-xs muted mt-1">
            from run <span className="font-mono">{featured.run_id}</span> (this is the inter-judge
            stand-in, not the calibration-probe ground truth — useful for showing how coverage
            scales with α).
          </div>
        )}
        <div className="mt-3">
          <Card>
            <ParetoChart data={pareto} />
          </Card>
        </div>
      </section>

      <section>
        <CardTitle>methodology</CardTitle>
        <Card className="mt-3">
          <ul className="text-sm leading-relaxed list-disc pl-6 space-y-2 muted">
            {calib.methodology_notes.map((n, i) => (
              <li key={i}>{n}</li>
            ))}
          </ul>
        </Card>
      </section>

      <section>
        <CardTitle>judges</CardTitle>
        <div className="mt-3 grid md:grid-cols-2 gap-4">
          {calib.judges.map((j) => (
            <Card key={j.judge_id}>
              <JudgeBadge judgeId={j.judge_id} />
              <div className="mt-3 text-sm">
                {j.valid_scores}/{j.total_calls} valid scores
              </div>
              {j.note && (
                <div className="mt-2 text-xs muted leading-relaxed">{j.note}</div>
              )}
            </Card>
          ))}
        </div>
      </section>

      <section>
        <CardTitle>candidate generation</CardTitle>
        <Card className="mt-3">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div>
              <div className="text-xs muted">model</div>
              <div className="font-mono">{calib.generator.model}</div>
            </div>
            <div>
              <div className="text-xs muted">temperature</div>
              <div className="font-mono">{calib.generator.temperature}</div>
            </div>
            <div>
              <div className="text-xs muted">pass rate</div>
              <div className="font-mono text-emerald-500">
                {formatPercent(calib.candidates.pass_rate, 0)}
              </div>
            </div>
            <div>
              <div className="text-xs muted">passes / fails</div>
              <div className="font-mono">
                {calib.candidates.n_pass} / {calib.candidates.n_fail}
              </div>
            </div>
          </div>
        </Card>
      </section>
    </div>
  );
}
